export const RETRIEVE_ASSOCIATED_BEACONS = 'RETRIEVE_ASSOCIATED_BEACONS';
export const ADD_TO_ASSOCIATED_BEACONS = 'ADD_TO_ASSOCIATED_BEACONS';
export const REMOVE_FROM_ASSOCIATED_BEACONS = 'REMOVE_FROM_ASSOCIATED_BEACONS';
export const SET_SCANNER_TO_NOT_SCANNING = 'SET_SCANNER_TO_NOT_SCANNING';
export const SET_SCANNER_TO_SCANNING = 'SET_SCANNER_TO_SCANNING';
export const SET_REGION_TO_SEARCHFOR_IOS = 'SET_REGION_TO_SEARCHFOR_IO';
export const GET_REGION_TO_SEARCHFOR_IOS = 'GET_REGION_TO_SEARCHFOR_IO';